sudo: required
addons:
  chrome: stable
language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - '8'
script:
  - CHROME_HEADLESS=1 npm run test
branches:
  except:
    - /.*v\d+\.\d+\.\d.*$/